### PR TITLE
fix wrong alignment

### LINKED ISSUE #227: Some recent change broke alignment
PIConGPU recently updated to `dev` branch of mallocMC and started reliably crashing in 2d simulations: https://github.com/ComputationalRadiationPhysics/picongpu/issues/3891 . I've narrowed down the crash to this update of mallocMC inside PIConGPU. So probably one of the recent PRs #217 - #226 introduced some bug that's causing it. The fact it's 2d in PIConGPU may be a conincidence or just one situation it appears.

We need to figure out and solve it quickly, as current PIConGPU `dev` and the release candidate branch are now impossible (or unreliable) to use for 2d because of this bug.

### PR DESCRIPTION
**Pull request by psychocoderHPC**
fix #227 and is a replacement for #228

In cases where the data allocation size is smaller than the minimum chunk size, the allocation size will be set to minimal chunk size.
In such cases, the alignment of the data can be wrong.

mallocMC inerface changes (not visible for the user):
- CreationPolicy::create() get the alignment policy as first template parameter
- AlignmentPolicy::applyPadding() requires 32bit input sizes and returns the size as 32bit value. (avoid cast operations)

Note: The changes will not increase the register-footprint (tested with PIConGPU)

### CODE REVIEW

File: src/include/mallocMC/creationPolicies/Scatter.hpp [hunk 1]
```diff
@@ -174,6 +174,8 @@ namespace mallocMC
              * fragment the heap and increases the possibility that a small allocation can reuse an
              * existing chunk.
              * Each page can have 32x32 chunks. To maintain 32 chunks we need 32 bitmask on the page (each 32bit)
+             *
+             * Attention: There is no requirement that minChunksSize is a power of two.
```
Comment (sbastrakov) [inline src/include/mallocMC/creationPolicies/Scatter.hpp]: It's more of a `@note` than attention, but no big deal

**Review by sbastrakov — APPROVED** [review]

**Comment by sbastrakov** [comment]
I did testing with PIConGPU, with this PR the issue https://github.com/ComputationalRadiationPhysics/picongpu/issues/3891 disappeared.
